name:                Huffman
version:             0.1.0.0
github:              "githubuser/Huffman"
license:             BSD3
author:              "Szymon Wróbel"
maintainer:          "szywro5@gmail.com"
copyright:           "2018 Szymon Wróbel"

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- pqueue >= 1.4.1.1
- containers >= 0.5.10.2
- bytestring >= 0.10.8.2
- binary == 0.8.5.1

library:
  source-dirs: src

executables:
  huffman-encode:
    main:                encode/Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Huffman
  huffman-decode:
    main:                decode/Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Huffman

tests:
  Huffman-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Huffman
