name:                Huffman
version:             0.1.0.0
github:              "githubuser/Huffman"
license:             BSD3
author:              "Szymon Wróbel"
maintainer:          "szywro5@gmail.com"
copyright:           "2018 Szymon Wróbel"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Huffman#readme>

dependencies:
- base >= 4.7 && < 5
- pqueue >= 1.4.1.1

library:
  source-dirs: src

executables:
  huffman-encode:
    main:                Encode.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Huffman
  huffman-decode:
    main:                Decode.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Huffman

tests:
  Huffman-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Huffman
